# Server Configuration
server.port=8080

# Google Gemini API Configuration
# google.gemini.api.key=${GEMINI_API_KEY:AIzaSyDKIj7n0GOAxhOrdFGQFJJcg4_mHsRmlhM}
# google.gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions

